In [61]:
import pandas as pd 
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

In [9]:
fs_df = pd.read_csv('../data/Most-Recent-Cohorts-Field-of-Study.csv')

In [10]:
data_dict = pd.read_excel('../data/collegescorecarddatadictionary_01192021-1.xlsx', sheet_name=None)

In [14]:
fs_df.head()

,UNITID,OPEID6,INSTNM,CONTROL,MAIN,CIPCODE,CIPDESC,CREDLEV,CREDDESC,IPEDSCOUNT1,...,EARN_MDN_HI_2YR,BBRR2_FED_COMP_N,BBRR2_FED_COMP_DFLT,BBRR2_FED_COMP_DLNQ,BBRR2_FED_COMP_FBR,BBRR2_FED_COMP_DFR,BBRR2_FED_COMP_NOPROG,BBRR2_FED_COMP_MAKEPROG,BBRR2_FED_COMP_PAIDINFULL,BBRR2_FED_COMP_DISCHARGE
0,100654.0,1002,Alabama A & M University,Public,1,100,"Agriculture, General.",3,Bachelors Degree,NaN,...,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed
1,100654.0,1002,Alabama A & M University,Public,1,109,Animal Sciences.,3,Bachelors Degree,6.0,...,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed
2,100654.0,1002,Alabama A & M University,Public,1,110,Food Science and Technology.,3,Bachelors Degree,8.0,...,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed
3,100654.0,1002,Alabama A & M University,Public,1,110,Food Science and Technology.,5,Master's Degree,10.0,...,PrivacySuppressed,12,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed
4,100654.0,1002,Alabama A & M University,Public,1,110,Food Science and Technology.,6,Doctoral Degree,4.0,...,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed

In [15]:
fs_df.shape

(260531, 92)

In [16]:
data_dict.keys()

dict_keys(['README', 'ChangeLog', 'glossary', 'institution_cohort_map', 'institution_data_dictionary', 'most_recent_inst_cohort_map', 'FieldOfStudy_data_dictionary', 'FieldOfStudy_cohort_map'])

In [17]:
data_dict1= data_dict['FieldOfStudy_data_dictionary']

In [19]:
data_dict1.head()

,NAME OF DATA ELEMENT,dev-category,developer-friendly name,API data type,VARIABLE NAME,VALUE,LABEL,SOURCE,NOTES
0,Unit ID for institution,programs,cip_4_digit.unit_id,integer,UNITID,NaN,NaN,IPEDS,Shown/used on consumer website.
1,6-digit OPE ID for institution,programs,cip_4_digit.ope6_id,string,OPEID6,NaN,NaN,IPEDS/PEPS,NaN
2,Institution name,programs,cip_4_digit.school.name,autocomplete,INSTNM,NaN,NaN,IPEDS/PEPS,NaN
3,Control of institution,programs,cip_4_digit.school.type,integer,CONTROL,1.0,Public,IPEDS/PEPS,NaN
4,NaN,NaN,NaN,NaN,NaN,2.0,Private nonprofit,NaN,NaN

In [20]:
# Columns selected for field study df1 
columns = ['UNITID', 'INSTNM', 'CONTROL', 'CIPCODE', 'CIPDESC',  'CREDLEV', 'CREDDESC', 'DEBT_ALL_STGP_EVAL_MEAN', 'DEBT_ALL_STGP_EVAL_MDN']

In [21]:
fs_df1 = df[columns]

In [22]:
fs_df1.head()

,UNITID,INSTNM,CONTROL,CIPCODE,CIPDESC,CREDLEV,CREDDESC,DEBT_ALL_STGP_EVAL_MEAN,DEBT_ALL_STGP_EVAL_MDN
0,100654.0,Alabama A & M University,Public,100,"Agriculture, General.",3,Bachelors Degree,PrivacySuppressed,PrivacySuppressed
1,100654.0,Alabama A & M University,Public,109,Animal Sciences.,3,Bachelors Degree,PrivacySuppressed,PrivacySuppressed
2,100654.0,Alabama A & M University,Public,110,Food Science and Technology.,3,Bachelors Degree,PrivacySuppressed,PrivacySuppressed
3,100654.0,Alabama A & M University,Public,110,Food Science and Technology.,5,Master's Degree,PrivacySuppressed,PrivacySuppressed
4,100654.0,Alabama A & M University,Public,110,Food Science and Technology.,6,Doctoral Degree,PrivacySuppressed,PrivacySuppressed

In [24]:
fs_df1.DEBT_ALL_STGP_EVAL_MDN[fs_df1.DEBT_ALL_STGP_EVAL_MDN == 'PrivacySuppressed'].count()

208870

In [26]:
fs_df1.DEBT_ALL_STGP_EVAL_MEAN[fs_df1.DEBT_ALL_STGP_EVAL_MEAN == 'PrivacySuppressed'].count()

210452

In [28]:
filt = (fs_df1.DEBT_ALL_STGP_EVAL_MEAN == 'PrivacySuppressed') | (fs_df1.DEBT_ALL_STGP_EVAL_MDN == 'PrivacySuppressed')
fs_df1.shape[0]-fs_df1.DEBT_ALL_STGP_EVAL_MEAN[filt].count()

38947

In [30]:
inst_df = pd.read_csv('../data/Most-Recent-Cohorts-All-Data-Elements.csv')

/home/ana/Projects/StudentDebtForecaster/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3155: DtypeWarning: Columns (9,1547,1589,1595,1596,1597,1598,1601,1602,1608,1619,1620,1621,1622,1623,1624,1625,1626,1627,1628,1629,1640,1643,1648,1653,1657,1664,1665,1666,1669,1670,1674,1679,1683,1688,1689,1690,1691,1692,1697,1700,1702,1703,1704,1705,1706,1707,1725,1726,1727,1728,1729,1743,1815,1816,1817,1818,1823,1824,1830,1831,1846,1879,1880,1881,1882,1883,1884,1885,1886,1887,1888,1889,1890,1891,1892,1893,1894,1895,1896,1897,1898,1909,1910,1911,1912,1913,1957,1958,1959,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1983,1984,2376,2377) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [31]:
inst_df.shape

(6806, 2384)

In [32]:
inst_df.head()

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,ZIP,ACCREDAGENCY,INSTURL,NPCURL,...,BBRR2_FED_UGCOMP_PAIDINFULL_SUPP,BBRR2_FED_UGCOMP_DISCHARGE_SUPP,LPSTAFFORD_CNT,LPSTAFFORD_AMT,LPPPLUS_CNT,LPPPLUS_AMT,LPGPLUS_CNT,LPGPLUS_AMT,FEDSCHCD,SEARCH_STRING
0,100654,100200,1002,Alabama A & M University,Normal,AL,35762,Southern Association of Colleges and Schools C...,www.aamu.edu/,www.aamu.edu/admissions-aid/tuition-fees/net-p...,...,PrivacySuppressed,PrivacySuppressed,31374,922456254,5201,113949554,1004,15578483,001002,Alabama A & M University AAMU
1,100663,105200,1052,University of Alabama at Birmingham,Birmingham,AL,35294-0110,Southern Association of Colleges and Schools C...,https://www.uab.edu,https://uab.studentaidcalculator.com/survey.aspx,...,0.06289779108947,PrivacySuppressed,56997,1720042015,3727,87421879,3461,134126588,001052,University of Alabama at Birmingham
2,100690,2503400,25034,Amridge University,Montgomery,AL,36117-3553,Southern Association of Colleges and Schools C...,www.amridgeuniversity.edu,www2.amridgeuniversity.edu:9091/,...,PrivacySuppressed,PrivacySuppressed,4463,174222020,16,309618,298,16290781,016885,Amridge University Southern Christian Universi...
3,100706,105500,1055,University of Alabama in Huntsville,Huntsville,AL,35899,Southern Association of Colleges and Schools C...,www.uah.edu,finaid.uah.edu/,...,0.09598603839441,PrivacySuppressed,19702,407184805,1397,29789762,144,2377759,001055,University of Alabama in Huntsville UAH Unive...
4,100724,100500,1005,Alabama State University,Montgomery,AL,36104-0271,Southern Association of Colleges and Schools C...,www.alasu.edu,www.alasu.edu/cost-aid/tuition-costs/net-price...,...,PrivacySuppressed,PrivacySuppressed,34246,947070736,4602,95359062,587,12174367,001005,Alabama State University

In [40]:
# columns to be selected from inst_df 
inst_cols = ['UNITID', 'CITY', 'STABBR', 'ACCREDAGENCY', 'CONTROL', 'COSTT4_A', 'COSTT4_P', 'TUITIONFEE_IN', 
             'TUITIONFEE_OUT', 'PFTFAC', 'PCTPELL', 'GRAD_DEBT_MDN', 'WDRAW_DEBT_MDN',
             'LO_INC_DEBT_MDN', 'MD_INC_DEBT_MDN', 'HI_INC_DEBT_MDN', 'DEP_DEBT_MDN', 'IND_DEBT_MDN',
             'PELL_DEBT_MDN', 'NOPELL_DEBT_MDN', 'FEMALE_DEBT_MDN', 'MALE_DEBT_MDN', 'FIRSTGEN_DEBT_MDN',
             'NOTFIRSTGEN_DEBT_MDN']

In [38]:
inst_df1 = inst_df[inst_cols]

In [41]:
inst_df1.head().T

,0,1,2,3,4
UNITID,100654,100663,100690,100706,100724
CITY,Normal,Birmingham,Montgomery,Huntsville,Montgomery
STABBR,AL,AL,AL,AL,AL
ACCREDAGENCY,Southern Association of Colleges and Schools C...,Southern Association of Colleges and Schools C...,Southern Association of Colleges and Schools C...,Southern Association of Colleges and Schools C...,Southern Association of Colleges and Schools C...
CONTROL,1,1,2,1,1
COSTT4_A,22489.0,24347.0,17680.0,23441.0,21476.0
COSTT4_P,NaN,NaN,NaN,NaN,NaN
TUITIONFEE_IN,9744.0,8568.0,6900.0,10714.0,11068.0
TUITIONFEE_OUT,18354.0,19704.0,6900.0,22362.0,19396.0
PFTFAC,0.7411,0.7766,1.0,0.6544,0.5826
PCTPELL,0.7067,0.3632,0.7673,0.2698,0.7448
GRAD_DEBT_MDN,33375,22500,27334,21607,32000
WDRAW_DEBT_MDN,10250,9500,9500,9000,11161
LO_INC_DEBT_MDN,15500,16226,9500,16250,18750
MD_INC_DEBT_MDN,16000,15250,19000,14750,18500
HI_INC_DEBT_MDN,14518,14000,25000,12500,18246
DEP_DEBT_MDN,15000,15000,7646,12750,17500
IND_DEBT_MDN,19000,16000,12038,18569,23925
PELL_DEBT_MDN,17500,17500,9500,17014,19056
NOPELL_DEBT_MDN,10250,12500,15509,11899,12000
FEMALE_DEBT_MDN,17500,15000,9500,15250,19500
MALE_DEBT_MDN,14250,15000,17025,13333,15525
FIRSTGEN_DEBT_MDN,15000,15104,11500,14943,19000
NOTFIRSTGEN_DEBT_MDN,16421,15000,9500,13102,17500

In [43]:
data_dict1

,NAME OF DATA ELEMENT,dev-category,developer-friendly name,API data type,VARIABLE NAME,VALUE,LABEL,SOURCE,NOTES
0,Unit ID for institution,programs,cip_4_digit.unit_id,integer,UNITID,NaN,NaN,IPEDS,Shown/used on consumer website.
1,6-digit OPE ID for institution,programs,cip_4_digit.ope6_id,string,OPEID6,NaN,NaN,IPEDS/PEPS,NaN
2,Institution name,programs,cip_4_digit.school.name,autocomplete,INSTNM,NaN,NaN,IPEDS/PEPS,NaN
3,Control of institution,programs,cip_4_digit.school.type,integer,CONTROL,1.0,Public,IPEDS/PEPS,NaN
4,NaN,NaN,NaN,NaN,NaN,2.0,Private nonprofit,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,3.0,Private for-profit,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,4.0,Foreign,NaN,NaN
7,Flag for main campus,programs,cip_4_digit.school.main_campus,integer,MAIN,0.0,Not main campus,IPEDS/PEPS,Shown/used on consumer website.
8,NaN,NaN,NaN,NaN,NaN,1.0,Main campus,NaN,NaN
9,Classification of Instructional Programs (CIP)...,programs,cip_4_digit.code,string,CIPCODE,NaN,NaN,NSLDS,Shown/used on consumer website.
10,Text description of the field of study CIP Code,programs,cip_4_digit.title,string,CIPDESC,NaN,NaN,ED,Shown/used on consumer website.
11,Level of credential,programs,cip_4_digit.credential.level,integer,CREDLEV,1.0,Undergraduate Certificate or Diploma,NSLDS,Shown/used on consumer website.
12,NaN,NaN,NaN,NaN,NaN,2.0,Associate's Degree,NSLDS,NaN
13,NaN,NaN,NaN,NaN,NaN,3.0,Bachelorâ€™s Degree,NSLDS,NaN
14,NaN,NaN,NaN,NaN,NaN,4.0,Post-baccalaureate Certificate,NSLDS,NaN
15,NaN,NaN,NaN,NaN,NaN,5.0,Master's Degree,NSLDS,NaN
16,NaN,NaN,NaN,NaN,NaN,6.0,Doctoral Degree,NSLDS,NaN
17,NaN,NaN,NaN,NaN,NaN,7.0,First Professional Degree,NSLDS,NaN
18,NaN,NaN,NaN,NaN,NaN,8.0,Graduate/Professional Certificate,NSLDS,NaN
19,Text description of the level of credential,programs,cip_4_digit.credential.title,string,CREDDESC,NaN,NaN,NSLDS,Shown/used on consumer website.
20,Number of awards to all students in year 1 of ...,programs,cip_4_digit.counts.ipeds_awards1,integer,IPEDSCOUNT1,NaN,NaN,IPEDS,NaN
21,Number of awards to all students in year 2 of ...,programs,cip_4_digit.counts.ipeds_awards2,integer,IPEDSCOUNT2,NaN,NaN,IPEDS,Shown/used on consumer website.
22,Student recipient count for average/median Par...,programs,cip_4_digit.debt.parent_plus.all.all_inst.count,integer,DEBT_ALL_PP_ANY_N,NaN,NaN,NSLDS,NaN
23,Average Parent PLUS loan debt disbursed at all...,programs,cip_4_digit.debt.parent_plus.all.all_inst.average,integer,DEBT_ALL_PP_ANY_MEAN,NaN,NaN,NSLDS,NaN
24,Median Parent PLUS loan debt disbursed at all ...,programs,cip_4_digit.debt.parent_plus.all.all_inst.median,integer,DEBT_ALL_PP_ANY_MDN,NaN,NaN,NSLDS,NaN
25,Student recipient count for average/median Par...,programs,cip_4_digit.debt.parent_plus.male.all_inst.count,integer,DEBT_MALE_PP_ANY_N,NaN,NaN,NSLDS,NaN
26,Average Parent PLUS loan debt disbursed to mal...,programs,cip_4_digit.debt.parent_plus.male.all_inst.ave...,integer,DEBT_MALE_PP_ANY_MEAN,NaN,NaN,NSLDS,NaN
27,Median Parent PLUS loan debt disbursed to male...,programs,cip_4_digit.debt.parent_plus.male.all_inst.median,integer,DEBT_MALE_PP_ANY_MDN,NaN,NaN,NSLDS,NaN
28,Student recipient count for average/median Par...,programs,cip_4_digit.debt.parent_plus.not_male.all_inst...,integer,DEBT_NOTMALE_PP_ANY_N,NaN,NaN,NSLDS,NaN
29,Average Parent PLUS loan debt disbursed to non...,programs,cip_4_digit.debt.parent_plus.not_male.all_inst...,integer,DEBT_NOTMALE_PP_ANY_MEAN,NaN,NaN,NSLDS,NaN
30,Median Parent PLUS loan debt disbursed to non-...,programs,cip_4_digit.debt.parent_plus.not_male.all_inst...,integer,DEBT_NOTMALE_PP_ANY_MDN,NaN,NaN,NSLDS,NaN
31,Student recipient count for average/median Par...,programs,cip_4_digit.debt.parent_plus.pell.all_inst.count,integer,DEBT_PELL_PP_ANY_N,NaN,NaN,NSLDS,NaN
32,Average Parent PLUS loan debt disbursed to Pel...,programs,cip_4_digit.debt.parent_plus.pell.all_inst.ave...,integer,DEBT_PELL_PP_ANY_MEAN,NaN,NaN,NSLDS,NaN
33,Median Parent PLUS loan debt disbursed to Pell...,programs,cip_4_digit.debt.parent_plus.pell.all_inst.median,integer,DEBT_PELL_PP_ANY_MDN,NaN,NaN,NSLDS,NaN
34,Student recipient count for average/median Par...,programs,cip_4_digit.debt.parent_plus.not_pell.all_inst...,integer,DEBT_NOPELL_PP_ANY_N,NaN,NaN,NSLDS,NaN
35,Average Parent PLUS loan debt disbursed to non...,programs,cip_4_digit.debt.parent_plus.not_pell.all_inst...,integer,DEBT_NOPELL_PP_ANY_MEAN,NaN,NaN,NSLDS,NaN
36,Median Parent PLUS loan debt disbursed to non-...,programs,cip_4_digit.debt.parent_plus.not_pell.all_inst...,integer,DEBT_NOPELL_PP_ANY_MDN,NaN,NaN,NSLDS,NaN
37,Student recipient count for average/median Par...,programs,cip_4_digit.debt.parent_plus.all.eval_inst.count,integer,DEBT_ALL_PP_EVAL_N,NaN,NaN,NSLDS,NaN
38,Average Parent PLUS loan debt disbursed at thi...,programs,cip_4_digit.debt.parent_plus.all.eval_inst.ave...,integer,DEBT_ALL_PP_EVAL_MEAN,NaN,NaN,NSLDS,NaN
39,Median Parent PLUS loan debt disbursed at this...,programs,cip_4_digit.debt.parent_plus.all.eval_inst.median,integer,DEBT_ALL_PP_EVAL_MDN,NaN,NaN,NSLDS,NaN
40,Student recipient count for average/median Par...,programs,cip_4_digit.debt.parent_plus.male.eval_inst.count,integer,DEBT_MALE_PP_EVAL_N,NaN,NaN,NSLDS,NaN
41,Average Parent PLUS loan debt disbursed to mal...,programs,cip_4_digit.debt.parent_plus.male.eval_inst.av...,integer,DEBT_MALE_PP_EVAL_MEAN,NaN,NaN,NSLDS,NaN
42,Median Parent PLUS loan debt disbursed to male...,programs,cip_4_digit.debt.parent_plus.male.eval_inst.me...,integer,DEBT_MALE_PP_EVAL_MDN,NaN,NaN,NSLDS,NaN
43,Student recipient count for average/median Par...,programs,cip_4_digit.debt.parent_plus.not_male.eval_ins...,integer,DEBT_NOTMALE_PP_EVAL_N,NaN,NaN,NSLDS,NaN
44,Average Parent PLUS loan debt disbursed to non...,programs,cip_4_digit.debt.parent_plus.not_male.eval_ins...,integer,DEBT_NOTMALE_PP_EVAL_MEAN,NaN,NaN,NSLDS,NaN
45,Median Parent PLUS loan debt disbursed to non-...,programs,cip_4_digit.debt.parent_plus.not_male.eval_ins...,integer,DEBT_NOTMALE_PP_EVAL_MDN,NaN,NaN,NSLDS,NaN
46,Student recipient count for average/median Par...,programs,cip_4_digit.debt.parent_plus.pell.eval_inst.count,integer,DEBT_PELL_PP_EVAL_N,NaN,NaN,NSLDS,NaN
47,Average Parent PLUS loan debt disbursed to Pel...,programs,cip_4_digit.debt.parent_plus.pell.eval_inst.av...,integer,DEBT_PELL_PP_EVAL_MEAN,NaN,NaN,NSLDS,NaN
48,Median Parent PLUS loan debt disbursed to Pell...,programs,cip_4_digit.debt.parent_plus.pell.eval_inst.me...,integer,DEBT_PELL_PP_EVAL_MDN,NaN,NaN,NSLDS,NaN
49,Student recipient count for average/median Par...,programs,cip_4_digit.debt.parent_plus.not_pell.eval_ins...,integer,DEBT_NOPELL_PP_EVAL_N,NaN,NaN,NSLDS,NaN
50,Average Parent PLUS loan debt disbursed to non...,programs,cip_4_digit.debt.parent_plus.not_pell.eval_ins...,integer,DEBT_NOPELL_PP_EVAL_MEAN,NaN,NaN,NSLDS,NaN
51,Median Parent PLUS loan debt disbursed to non-...,programs,cip_4_digit.debt.parent_plus.not_pell.eval_ins...,integer,DEBT_NOPELL_PP_EVAL_MDN,NaN,NaN,NSLDS,NaN
52,Borrower count for average/median Stafford and...,programs,cip_4_digit.debt.staff_grad_plus.all.all_inst....,integer,DEBT_ALL_STGP_ANY_N,NaN,NaN,NSLDS,NaN
53,Average Stafford and Grad PLUS loan debt disbu...,programs,cip_4_digit.debt.staff_grad_plus.all.all_inst....,integer,DEBT_ALL_STGP_ANY_MEAN,NaN,NaN,NSLDS,NaN
54,Median Stafford and Grad PLUS loan debt disbur...,programs,cip_4_digit.debt.staff_grad_plus.all.all_inst....,integer,DEBT_ALL_STGP_ANY_MDN,NaN,NaN,NSLDS,Shown/used on consumer website.
55,Borrower count for average/median Stafford and...,programs,cip_4_digit.debt.staff_grad_plus.male.all_inst...,integer,DEBT_MALE_STGP_ANY_N,NaN,NaN,NSLDS,NaN
56,Average Stafford and Grad PLUS loan debt disbu...,programs,cip_4_digit.debt.staff_grad_plus.male.all_inst...,integer,DEBT_MALE_STGP_ANY_MEAN,NaN,NaN,NSLDS,NaN
57,Median Stafford and Grad PLUS loan debt disbur...,programs,cip_4_digit.debt.staff_grad_plus.male.all_inst...,integer,DEBT_MALE_STGP_ANY_MDN,NaN,NaN,NSLDS,NaN
58,Borrower count for average/median Stafford and...,programs,cip_4_digit.debt.staff_grad_plus.not_male.all_...,integer,DEBT_NOTMALE_STGP_ANY_N,NaN,NaN,NSLDS,NaN
59,Average Stafford and Grad PLUS loan debt disbu...,programs,cip_4_digit.debt.staff_grad_plus.not_male.all_...,integer,DEBT_NOTMALE_STGP_ANY_MEAN,NaN,NaN,NSLDS,NaN
60,Median Stafford and Grad PLUS loan debt disbur...,programs,cip_4_digit.debt.staff_grad_plus.not_male.all_...,integer,DEBT_NOTMALE_STGP_ANY_MDN,NaN,NaN,NSLDS,NaN
61,Borrower count for average/median Stafford and...,programs,cip_4_digit.debt.staff_grad_plus.pell.all_inst...,integer,DEBT_PELL_STGP_ANY_N,NaN,NaN,NSLDS,NaN
62,Average Stafford and Grad PLUS loan debt disbu...,programs,cip_4_digit.debt.staff_grad_plus.pell.all_inst...,integer,DEBT_PELL_STGP_ANY_MEAN,NaN,NaN,NSLDS,NaN
63,Median Stafford and Grad PLUS loan debt disbur...,programs,cip_4_digit.debt.staff_grad_plus.pell.all_inst...,integer,DEBT_PELL_STGP_ANY_MDN,NaN,NaN,NSLDS,NaN
64,Borrower count for average/median Stafford and...,programs,cip_4_digit.debt.staff_grad_plus.not_pell.all_...,integer,DEBT_NOPELL_STGP_ANY_N,NaN,NaN,NSLDS,NaN
65,Average Stafford and Grad PLUS loan debt disbu...,programs,cip_4_digit.debt.staff_grad_plus.not_pell.all_...,integer,DEBT_NOPELL_STGP_ANY_MEAN,NaN,NaN,NSLDS,NaN
66,Median Stafford and Grad PLUS loan debt disbur...,programs,cip_4_digit.debt.staff_grad_plus.not_pell.all_...,integer,DEBT_NOPELL_STGP_ANY_MDN,NaN,NaN,NSLDS,NaN
67,Borrower count for average/median Stafford and...,programs,cip_4_digit.debt.staff_grad_plus.all.eval_inst...,integer,DEBT_ALL_STGP_EVAL_N,NaN,NaN,NSLDS,NaN
68,Average Stafford and Grad PLUS loan debt disbu...,programs,cip_4_digit.debt.staff_grad_plus.all.eval_inst...,integer,DEBT_ALL_STGP_EVAL_MEAN,NaN,NaN,NSLDS,NaN
69,Median Stafford and Grad PLUS loan debt disbur...,programs,cip_4_digit.debt.staff_grad_plus.all.eval_inst...,integer,DEBT_ALL_STGP_EVAL_MDN,NaN,NaN,NSLDS,Shown/used on consumer website.
70,Borrower count for average/median Stafford and...,programs,cip_4_digit.debt.staff_grad_plus.male.eval_ins...,integer,DEBT_MALE_STGP_EVAL_N,NaN,NaN,NSLDS,NaN
71,Average Stafford and Grad PLUS loan debt disbu...,programs,cip_4_digit.debt.staff_grad_plus.male.eval_ins...,integer,DEBT_MALE_STGP_EVAL_MEAN,NaN,NaN,NSLDS,NaN
72,Median Stafford and Grad PLUS loan debt disbur...,programs,cip_4_digit.debt.staff_grad_plus.male.eval_ins...,integer,DEBT_MALE_STGP_EVAL_MDN,NaN,NaN,NSLDS,NaN
73,Borrower count for average/median Stafford and...,programs,cip_4_digit.debt.staff_grad_plus.not_male.eval...,integer,DEBT_NOTMALE_STGP_EVAL_N,NaN,NaN,NSLDS,NaN
74,Average Stafford and Grad PLUS loan debt disbu...,programs,cip_4_digit.debt.staff_grad_plus.not_male.eval...,integer,DEBT_NOTMALE_STGP_EVAL_MEAN,NaN,NaN,NSLDS,NaN
75,Median Stafford and Grad PLUS loan debt disbur...,programs,cip_4_digit.debt.staff_grad_plus.not_male.eval...,integer,DEBT_NOTMALE_STGP_EVAL_MDN,NaN,NaN,NSLDS,NaN
76,Borrower count for average/median Stafford and...,programs,cip_4_digit.debt.staff_grad_plus.pell.eval_ins...,integer,DEBT_PELL_STGP_EVAL_N,NaN,NaN,NSLDS,NaN
77,Average Stafford and Grad PLUS loan debt disbu...,programs,cip_4_digit.debt.staff_grad_plus.pell.eval_ins...,integer,DEBT_PELL_STGP_EVAL_MEAN,NaN,NaN,NSLDS,NaN
78,Median Stafford and Grad PLUS loan debt disbur...,programs,cip_4_digit.debt.staff_grad_plus.pell.eval_ins...,integer,DEBT_PELL_STGP_EVAL_MDN,NaN,NaN,NSLDS,NaN
79,Borrower count for average/median Stafford and...,programs,cip_4_digit.debt.staff_grad_plus.not_pell.eval...,integer,DEBT_NOPELL_STGP_EVAL_N,NaN,NaN,NSLDS,NaN
80,Average Stafford and Grad PLUS loan debt disbu...,programs,cip_4_digit.debt.staff_grad_plus.not_pell.eval...,integer,DEBT_NOPELL_STGP_EVAL_MEAN,NaN,NaN,NSLDS,NaN
81,Median Stafford and Grad PLUS loan debt disbur...,programs,cip_4_digit.debt.staff_grad_plus.not_pell.eval...,integer,DEBT_NOPELL_STGP_EVAL_MDN,NaN,NaN,NSLDS,NaN
82,Median estimated monthly payment for Parent PL...,programs,cip_4_digit.debt.parent_plus.all.all_inst.medi...,float,DEBT_ALL_PP_ANY_MDN10YRPAY,NaN,NaN,NSLDS,NaN
83,Median estimated monthly payment for Parent PL...,programs,cip_4_digit.debt.parent_plus.all.eval_inst.med...,float,DEBT_ALL_PP_EVAL_MDN10YRPAY,NaN,NaN,NSLDS,NaN
84,Median estimated monthly payment for Stafford ...,programs,cip_4_digit.debt.staff_grad_plus.all.all_inst....,float,DEBT_ALL_STGP_ANY_MDN10YRPAY,NaN,NaN,NSLDS,NaN
85,Median estimated monthly payment for Stafford ...,programs,cip_4_digit.debt.staff_grad_plus.all.eval_inst...,float,DEBT_ALL_STGP_EVAL_MDN10YRPAY,NaN,NaN,NSLDS,NaN
86,Number of graduates not working and not enroll...,programs,cip_4_digit.earnings.highest.1_yr.not_working_...,integer,EARN_COUNT_NWNE_HI_1YR,NaN,NaN,Treasury,NaN
87,Number of graduates working and not enrolled 1...,programs,cip_4_digit.earnings.highest.1_yr.working_not_...,integer,EARN_COUNT_WNE_HI_1YR,NaN,NaN,Treasury,NaN
88,Median earnings of graduates working and not e...,programs,cip_4_digit.earnings.highest.1_yr.overall_medi...,integer,EARN_MDN_HI_1YR,NaN,NaN,Treasury,NaN
89,Number of graduates working and not enrolled w...,programs,cip_4_digit.earnings.highest.1_yr.overall_coun...,integer,EARN_CNTOVER150_HI_1YR,NaN,NaN,Treasury,NaN
90,Number of graduates not working and not enroll...,programs,cip_4_digit.earnings.highest.2_yr.not_working_...,integer,EARN_COUNT_NWNE_HI_2YR,NaN,NaN,Treasury,NaN
91,Number of graduates working and not enrolled 2...,programs,cip_4_digit.earnings.highest.2_yr.working_not_...,integer,EARN_COUNT_WNE_HI_2YR,NaN,NaN,Treasury,NaN
92,Median earnings of graduates working and not e...,programs,cip_4_digit.earnings.highest.2_yr.overall_medi...,integer,EARN_MDN_HI_2YR,NaN,NaN,Treasury,Shown/used on consumer website.
93,Number of graduates working and not enrolled w...,programs,cip_4_digit.earnings.highest.2_yr.overall_coun...,integer,EARN_CNTOVER150_HI_2YR,NaN,NaN,Treasury,NaN
94,Federal student loan borrower-based 2-year bor...,programs,cip_4_digit.repayment.2_yr_bb_fed_comp.count,integer,BBRR2_FED_COMP_N,NaN,NaN,NSLDS,NaN
95,Percentage of undergraduate completer undergra...,programs,cip_4_digit.repayment.2_yr_bb_fed_comp.default,float,BBRR2_FED_COMP_DFLT,NaN,NaN,NSLDS,NaN
96,Percentage of undergraduate completer undergra...,programs,cip_4_digit.repayment.2_yr_bb_fed_comp.delinquent,float,BBRR2_FED_COMP_DLNQ,NaN,NaN,NSLDS,NaN
97,Percentage of undergraduate completer undergra...,programs,cip_4_digit.repayment.2_yr_bb_fed_comp.forbear...,float,BBRR2_FED_COMP_FBR,NaN,NaN,NSLDS,NaN
98,Percentage of undergraduate completer undergra...,programs,cip_4_digit.repayment.2_yr_bb_fed_comp.deferment,float,BBRR2_FED_COMP_DFR,NaN,NaN,NSLDS,NaN
99,Percentage of undergraduate completer undergra...,programs,cip_4_digit.repayment.2_yr_bb_fed_comp.noprogress,float,BBRR2_FED_COMP_NOPROG,NaN,NaN,NSLDS,NaN
100,Percentage of undergraduate completer undergra...,programs,cip_4_digit.repayment.2_yr_bb_fed_comp.makingp...,float,BBRR2_FED_COMP_MAKEPROG,NaN,NaN,NSLDS,NaN
101,Percentage of undergraduate completer undergra...,programs,cip_4_digit.repayment.2_yr_bb_fed_comp.fullypaid,float,BBRR2_FED_COMP_PAIDINFULL,NaN,NaN,NSLDS,NaN
102,Percentage of undergraduate completer undergra...,programs,cip_4_digit.repayment.2_yr_bb_fed_comp.discharge,float,BBRR2_FED_COMP_DISCHARGE,NaN,NaN,NSLDS,NaN

In [48]:
#Reduce data dictionary for each df for convenience 
#Field of study data dict 
filt= data_dict1['VARIABLE NAME'].isin(columns)
fs_dictionary = data_dict1[filt]

In [65]:
fs_dictionary

,NAME OF DATA ELEMENT,dev-category,developer-friendly name,API data type,VARIABLE NAME,VALUE,LABEL,SOURCE,NOTES
0,Unit ID for institution,programs,cip_4_digit.unit_id,integer,UNITID,NaN,NaN,IPEDS,Shown/used on consumer website.
2,Institution name,programs,cip_4_digit.school.name,autocomplete,INSTNM,NaN,NaN,IPEDS/PEPS,NaN
3,Control of institution,programs,cip_4_digit.school.type,integer,CONTROL,1.0,Public,IPEDS/PEPS,NaN
9,Classification of Instructional Programs (CIP) code for the field of study,programs,cip_4_digit.code,string,CIPCODE,NaN,NaN,NSLDS,Shown/used on consumer website.
10,Text description of the field of study CIP Code,programs,cip_4_digit.title,string,CIPDESC,NaN,NaN,ED,Shown/used on consumer website.
11,Level of credential,programs,cip_4_digit.credential.level,integer,CREDLEV,1.0,Undergraduate Certificate or Diploma,NSLDS,Shown/used on consumer website.
19,Text description of the level of credential,programs,cip_4_digit.credential.title,string,CREDDESC,NaN,NaN,NSLDS,Shown/used on consumer website.
68,Average Stafford and Grad PLUS loan debt disbursed at this institution,programs,cip_4_digit.debt.staff_grad_plus.all.eval_inst.average,integer,DEBT_ALL_STGP_EVAL_MEAN,NaN,NaN,NSLDS,NaN
69,Median Stafford and Grad PLUS loan debt disbursed at this institution,programs,cip_4_digit.debt.staff_grad_plus.all.eval_inst.median,integer,DEBT_ALL_STGP_EVAL_MDN,NaN,NaN,NSLDS,Shown/used on consumer website.

In [66]:
inst_dict = data_dict['institution_data_dictionary']

In [67]:
filt = inst_dict['VARIABLE NAME'].isin(inst_cols)
inst_dict = inst_dict[filt]

In [68]:
inst_dict

,NAME OF DATA ELEMENT,dev-category,developer-friendly name,API data type,VARIABLE NAME,VALUE,LABEL,SOURCE,NOTES,Unnamed: 9,Unnamed: 10
4,City,school,city,autocomplete,CITY,NaN,NaN,IPEDS,Shown/used on consumer website.,NaN,NaN
5,State postcode,school,state,string,STABBR,NaN,NaN,IPEDS,Shown/used on consumer website.,NaN,NaN
7,Accreditor for institution,school,accreditor,string,ACCREDAGENCY,NaN,NaN,FSA,NaN,NaN,NaN
25,Control of institution,school,ownership,integer,CONTROL,1,Public,IPEDS,Shown/used on consumer website.,NaN,NaN
618,Average cost of attendance (academic year institutions),cost,attendance.academic_year,integer,COSTT4_A,NaN,NaN,IPEDS,"The average annual total cost of attendance, including tuition and fees, books and supplies, and living expenses for all full-time, first-time, degree/certificate-seeking undergraduates who receive Title IV aid. It is calculated from values in the IPEDS Institutional Characteristics and Student Financial Aid components. Separate metrics are calculated for academic-year institutions and program-year institutions. For academic-year institutions, average cost of attendance represents an average of all programs and includes only full-time, first-time, degree/certificate-seeking undergraduates who first enrolled in the fall term. For non-academic-year institutions (program or continuous enrollment), average cost of attendance represents the program with the largest enrollment at the institution, and it includes full-time, first-time, degree/certificate-seeking undergraduates who first enrolled at any time during the academic year. For programs less than 1 year in length (see LProgram), this represents the cost for the full program.",NaN,NaN
619,Average cost of attendance (program-year institutions),cost,attendance.program_year,integer,COSTT4_P,NaN,NaN,IPEDS,ibid,NaN,NaN
620,In-state tuition and fees,cost,tuition.in_state,integer,TUITIONFEE_IN,NaN,NaN,IPEDS,NaN,NaN,NaN
621,Out-of-state tuition and fees,cost,tuition.out_of_state,integer,TUITIONFEE_OUT,NaN,NaN,IPEDS,NaN,NaN,NaN
626,Proportion of faculty that is full-time,school,ft_faculty_rate,float,PFTFAC,NaN,NaN,IPEDS,"Proportion of faculty that are employed full time, calculated from the IPEDS Human Resources component. This metric is calculated as the number of full-time nonmedical faculty divided by the total number of nonmedical faculty. Proportions are expressed as decimals rounded to four decimal places, so, for example, 0.1234 equals 12.34 percent.",NaN,NaN
627,Percentage of undergraduates who receive a Pell Grant,aid,pell_grant_rate,float,PCTPELL,NaN,NaN,IPEDS,"The proportion of undergraduates who received a Pell grant in the academic year, calculated from the IPEDS Student Financial Aid component. This metric is calculated by IPEDS as the quotient of the number of Pell grant recipients divided by the count of all undergraduates for either a fall enrollment cohort (for institutions that primarily follow an academic year calendar system) or a full-year enrollment cohort (for institutions that primarily follow a continuous enrollment or program-based calendar system). Proportions are expressed as decimals rounded to four decimal places, so, for example, 0.1234 equals 12.34 percent. This metric is not available prior to the 2008-09 academic year.",NaN,NaN
1746,The median debt for students who have completed,aid,median_debt.completers.overall,float,GRAD_DEBT_MDN,NaN,NaN,NSLDS,NaN,NaN,NaN
1747,The median debt for students who have not completed,aid,median_debt.noncompleters,float,WDRAW_DEBT_MDN,NaN,NaN,NSLDS,NaN,NaN,NaN
1748,"The median debt for students with family income between $0-$30,000",aid,median_debt.income.0_30000,float,LO_INC_DEBT_MDN,NaN,NaN,NSLDS,NaN,NaN,NaN
1749,"The median debt for students with family income between $30,001-$75,000",aid,median_debt.income.30001_75000,float,MD_INC_DEBT_MDN,NaN,NaN,NSLDS,NaN,NaN,NaN
1750,"The median debt for students with family income $75,001+",aid,median_debt.income.greater_than_75000,float,HI_INC_DEBT_MDN,NaN,NaN,NSLDS,NaN,NaN,NaN
1751,The median debt for dependent students,aid,median_debt.dependent_students,float,DEP_DEBT_MDN,NaN,NaN,NSLDS,NaN,NaN,NaN
1752,The median debt for independent students,aid,median_debt.independent_students,float,IND_DEBT_MDN,NaN,NaN,NSLDS,NaN,NaN,NaN
1753,The median debt for Pell students,aid,median_debt.pell_grant,float,PELL_DEBT_MDN,NaN,NaN,NSLDS,NaN,NaN,NaN
1754,The median debt for no-Pell students,aid,median_debt.no_pell_grant,float,NOPELL_DEBT_MDN,NaN,NaN,NSLDS,NaN,NaN,NaN
1755,The median debt for female students,aid,median_debt.female_students,float,FEMALE_DEBT_MDN,NaN,NaN,NSLDS,NaN,NaN,NaN
1756,The median debt for male students,aid,median_debt.male_students,float,MALE_DEBT_MDN,NaN,NaN,NSLDS,NaN,NaN,NaN
1757,The median debt for first-generation students,aid,median_debt.first_generation_students,float,FIRSTGEN_DEBT_MDN,NaN,NaN,NSLDS,NaN,NaN,NaN
1758,The median debt for not-first-generation students,aid,median_debt.non_first_generation_students,float,NOTFIRSTGEN_DEBT_MDN,NaN,NaN,NSLDS,NaN,NaN,NaN

In [73]:
inst_df1.head(2)

,UNITID,CITY,STABBR,ACCREDAGENCY,CONTROL,COSTT4_A,COSTT4_P,TUITIONFEE_IN,TUITIONFEE_OUT,PFTFAC,PCTPELL,GRAD_DEBT_MDN,WDRAW_DEBT_MDN,LO_INC_DEBT_MDN,MD_INC_DEBT_MDN,HI_INC_DEBT_MDN,DEP_DEBT_MDN,IND_DEBT_MDN,PELL_DEBT_MDN,NOPELL_DEBT_MDN,FEMALE_DEBT_MDN,MALE_DEBT_MDN,FIRSTGEN_DEBT_MDN,NOTFIRSTGEN_DEBT_MDN
0,100654,Normal,AL,Southern Association of Colleges and Schools Commission on Colleges,1,22489.0,NaN,9744.0,18354.0,0.7411,0.7067,33375,10250,15500,16000,14518,15000,19000,17500,10250,17500,14250,15000,16421
1,100663,Birmingham,AL,Southern Association of Colleges and Schools Commission on Colleges,1,24347.0,NaN,8568.0,19704.0,0.7766,0.3632,22500,9500,16226,15250,14000,15000,16000,17500,12500,15000,15000,15104,15000

In [84]:
inst_df1.UNITID.nunique()

6806

In [86]:
inst_df1.CONTROL.value_counts() #1 Public, 2 Private non-profit, 3 private for-profit

3    2698
1    2102
2    2006
Name: CONTROL, dtype: int64

In [97]:
inst_df1.isna().sum()

UNITID                     0
CITY                       0
STABBR                     0
ACCREDAGENCY             354
CONTROL                    0
COSTT4_A                3375
COSTT4_P                4631
TUITIONFEE_IN           2941
TUITIONFEE_OUT          3185
PFTFAC                  3183
PCTPELL                  792
GRAD_DEBT_MDN            121
WDRAW_DEBT_MDN           121
LO_INC_DEBT_MDN          121
MD_INC_DEBT_MDN          121
HI_INC_DEBT_MDN          121
DEP_DEBT_MDN             121
IND_DEBT_MDN             121
PELL_DEBT_MDN            121
NOPELL_DEBT_MDN          121
FEMALE_DEBT_MDN          121
MALE_DEBT_MDN            121
FIRSTGEN_DEBT_MDN        121
NOTFIRSTGEN_DEBT_MDN     121
dtype: int64

In [100]:
inst_df1.head(81)

,UNITID,CITY,STABBR,ACCREDAGENCY,CONTROL,COSTT4_A,COSTT4_P,TUITIONFEE_IN,TUITIONFEE_OUT,PFTFAC,PCTPELL,GRAD_DEBT_MDN,WDRAW_DEBT_MDN,LO_INC_DEBT_MDN,MD_INC_DEBT_MDN,HI_INC_DEBT_MDN,DEP_DEBT_MDN,IND_DEBT_MDN,PELL_DEBT_MDN,NOPELL_DEBT_MDN,FEMALE_DEBT_MDN,MALE_DEBT_MDN,FIRSTGEN_DEBT_MDN,NOTFIRSTGEN_DEBT_MDN
0,100654,Normal,AL,Southern Association of Colleges and Schools Commission on Colleges,1,22489.0,NaN,9744.0,18354.0,0.7411,0.7067,33375,10250,15500,16000,14518,15000,19000,17500,10250,17500,14250,15000,16421
1,100663,Birmingham,AL,Southern Association of Colleges and Schools Commission on Colleges,1,24347.0,NaN,8568.0,19704.0,0.7766,0.3632,22500,9500,16226,15250,14000,15000,16000,17500,12500,15000,15000,15104,15000
2,100690,Montgomery,AL,Southern Association of Colleges and Schools Commission on Colleges,2,17680.0,NaN,6900.0,6900.0,1.0000,0.7673,27334,9500,9500,19000,25000,7646,12038,9500,15509,9500,17025,11500,9500
3,100706,Huntsville,AL,Southern Association of Colleges and Schools Commission on Colleges,1,23441.0,NaN,10714.0,22362.0,0.6544,0.2698,21607,9000,16250,14750,12500,12750,18569,17014,11899,15250,13333,14943,13102
4,100724,Montgomery,AL,Southern Association of Colleges and Schools Commission on Colleges,1,21476.0,NaN,11068.0,19396.0,0.5826,0.7448,32000,11161,18750,18500,18246,17500,23925,19056,12000,19500,15525,19000,17500
5,100751,Tuscaloosa,AL,Southern Association of Colleges and Schools Commission on Colleges,1,29424.0,NaN,10780.0,29230.0,0.7454,0.1802,23250,9500,17750,17750,17250,17500,15845,19500,15000,18500,16000,18000,16750
6,100760,Alexander City,AL,Southern Association of Colleges and Schools Commission on Colleges,1,8824.0,NaN,4740.0,8610.0,0.3966,0.4381,12500,6027,8000,7544,6256,5699,12500,8000,5625,9000,5500,7750,6500
7,100812,Athens,AL,Southern Association of Colleges and Schools Commission on Colleges,1,NaN,NaN,NaN,NaN,0.4601,0.4223,19500,10833,15250,13750,12500,11000,16666,15813,11750,14939,12500,14372,12501
8,100830,Montgomery,AL,Southern Association of Colleges and Schools Commission on Colleges,1,18291.0,NaN,8404.0,17812.0,0.9655,0.4584,24826,7514,11802,12500,12235,11189,13838,13000,11000,12982,10440,12375,12000
9,100858,Auburn,AL,Southern Association of Colleges and Schools Commission on Colleges,1,31282.0,NaN,11276.0,30524.0,0.8553,0.1537,21281,8250,17750,17750,16250,16849,18581,19000,15000,17750,16250,16750,17500
10,100937,Birmingham,AL,Southern Association of Colleges and Schools Commission on Colleges,2,52176.0,NaN,17650.0,17650.0,0.6667,0.2214,25773,5500,15250,19000,18500,PrivacySuppressed,PrivacySuppressed,19000,17500,19900,14250,18000,18500
11,101028,Phenix City,AL,Southern Association of Colleges and Schools Commission on Colleges,1,8750.0,NaN,4738.0,8608.0,0.3679,0.5463,11931,5500,6718,8360,5500,5500,9500,6941,6500,7444,6150,6687,6500
12,101116,Montgomery,AL,Southern Association of Colleges and Schools Commission on Colleges,3,29309.0,NaN,17014.0,17014.0,0.1467,0.6450,25166,9500,12728,15278,14833,11668,14250,14000,13000,14000,12667,13543,14460
13,101143,Enterprise,AL,Southern Association of Colleges and Schools Commission on Colleges,1,9262.0,NaN,4740.0,8610.0,0.4505,0.4207,8158,5526,5500,6498,7172,5500,7768,6497,5999,6458,6430,6497,6091
14,101161,Bay Minette,AL,Southern Association of Colleges and Schools Commission on Colleges,1,12008.0,NaN,4740.0,8610.0,0.6087,0.3696,11000,5500,5500,5500,5500,5500,8157,5500,5500,5500,5500,5500,5500
15,101189,Montgomery,AL,Southern Association of Colleges and Schools Commission on Colleges,2,33944.0,NaN,21690.0,21690.0,0.4534,0.4888,24363,8975,15250,14250,14250,11650,17000,15250,12875,16613,12000,14750,15000
16,101240,Gadsden,AL,Southern Association of Colleges and Schools Commission on Colleges,1,10098.0,NaN,3840.0,7056.0,0.4680,0.4943,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed
17,101277,Albertville,AL,National Accrediting Commission of Career Arts and Sciences,3,NaN,14301.0,NaN,NaN,NaN,0.7372,7000,3575,5500,PrivacySuppressed,PrivacySuppressed,5500,7375,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed
18,101286,Dothan,AL,Southern Association of Colleges and Schools Commission on Colleges,1,9564.0,NaN,4680.0,8550.0,0.5844,0.4934,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed
19,101295,Hanceville,AL,Southern Association of Colleges and Schools Commission on Colleges,1,10252.0,NaN,4740.0,8610.0,0.3839,0.4844,11000,6800,8888,8000,8250,6500,10500,8524,8250,9041,7000,8372,8056
20,101301,Selma,AL,Southern Association of Colleges and Schools Commission on Colleges,1,13788.0,NaN,4440.0,8310.0,0.5410,0.6689,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed
21,101365,Birmingham,AL,Higher Learning Commission,2,26128.0,NaN,14000.0,14000.0,0.5556,0.6370,22730,6920,10670,14620,16590,12444,12177,11554,15422,12188,12531,11965,13766
22,101435,Montgomery,AL,Southern Association of Colleges and Schools Commission on Colleges,2,35685.0,NaN,27400.0,27400.0,0.5714,0.4410,26399,6500,17365,17000,15000,14250,23977,17820,14583,19213,12500,17500,14000
23,101453,Florence,AL,Association for Bibical Higher Educaiton,2,NaN,NaN,11232.0,11232.0,1.0000,0.5517,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed
24,101462,Huntsville,AL,Southern Association of Colleges and Schools Commission on Colleges,1,11123.0,NaN,4710.0,8580.0,0.4462,0.6130,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed
25,101471,Deatsville,AL,Council on Occupational Education,1,5580.0,NaN,5328.0,5328.0,0.9825,0.2205,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,101480,Jacksonville,AL,Southern Association of Colleges and Schools Commission on Colleges,1,20050.0,NaN,8760.0,16536.0,0.6750,0.3882,23000,9500,15111,16421,14250,15000,15910,17305,12067,15856,14250,15645,14000
27,101505,Birmingham,AL,Southern Association of Colleges and Schools Commission on Colleges,1,13284.0,NaN,4800.0,8670.0,0.3162,0.2922,10000,4725,4500,5500,5500,5500,5500,4714,5500,5500,5500,5500,5500
28,101514,Tanner,AL,Southern Association of Colleges and Schools Commission on Colleges,1,9848.0,NaN,4820.0,8690.0,0.3197,0.3230,11250,5500,5500,6245,6231,5500,7484,5969,5500,6430,5500,5883,5500
29,101541,Marion,AL,Southern Association of Colleges and Schools Commission on Colleges,2,31735.0,NaN,18510.0,18510.0,0.3678,0.5302,26000,5500,15250,14861,10375,16875,10596,16738,8584,PrivacySuppressed,PrivacySuppressed,13500,25000
30,101569,Birmingham,AL,Southern Association of Colleges and Schools Commission on Colleges,1,13735.0,NaN,4740.0,8610.0,0.4107,0.6804,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed
31,101587,Livingston,AL,Southern Association of Colleges and Schools Commission on Colleges,1,20692.0,NaN,10040.0,18490.0,0.4906,0.5490,26299,10500,14250,12000,13000,15000,9501,15000,9500,14000,12000,13265,12375
32,101602,Andalusia,AL,Southern Association of Colleges and Schools Commission on Colleges,1,14136.0,NaN,4740.0,8610.0,0.6463,0.5052,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed
33,101648,Marion,AL,Southern Association of Colleges and Schools Commission on Colleges,1,18568.0,NaN,9418.0,15418.0,0.8800,0.4193,11750,5500,6250,5500,5500,5500,5938,5500,5500,5500,6250,5500,7875
34,101675,Fairfield,AL,Southern Association of Colleges and Schools Commission on Colleges,2,22828.0,NaN,12132.0,12132.0,0.7094,0.8636,30444,15179,15750,16895,15376,15293,18354,16000,11388,16486,15000,15250,18512
35,101693,Mobile,AL,Southern Association of Colleges and Schools Commission on Colleges,2,35463.0,NaN,23230.0,23230.0,1.0000,0.4310,27000,10500,22125,19500,18625,18750,24868,22354,16750,21250,18294,20225,19500
36,101709,Montevallo,AL,Southern Association of Colleges and Schools Commission on Colleges,1,24411.0,NaN,12760.0,25780.0,0.6667,0.3986,23500,9500,15375,17750,15000,15000,19000,18000,13405,17500,13692,16699,14250
37,101736,Muscle Shoals,AL,Southern Association of Colleges and Schools Commission on Colleges,1,12255.0,NaN,4711.0,8581.0,0.4845,0.4145,9750,5500,7500,5500,5500,5500,9500,6782,5220,6500,5500,6250,5500
38,101879,Florence,AL,Southern Association of Colleges and Schools Commission on Colleges,1,18712.0,NaN,10142.0,18452.0,1.0000,0.3983,23000,8734,14000,14770,15000,14500,15223,15500,13000,15000,14000,14500,14925
39,101897,Rainsville,AL,Southern Association of Colleges and Schools Commission on Colleges,1,8840.0,NaN,4740.0,8610.0,0.3333,0.4682,4815,3500,3250,4000,5500,3850,3944,3500,5500,3700,3938,3550,5500
40,101912,Huntsville,AL,Southern Association of Colleges and Schools Commission on Colleges,2,36361.0,NaN,19732.0,19732.0,0.7386,0.5024,30676,13000,18595,20000,20000,19500,18690,21250,12500,19500,19125,19000,19500
41,101994,Evergreen,AL,Council on Occupational Education,1,8958.0,NaN,4800.0,8670.0,0.5313,0.5204,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed
42,102030,Mobile,AL,Southern Association of Colleges and Schools Commission on Colleges,1,10155.0,NaN,4740.0,8610.0,0.5379,0.5435,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed
43,102049,Birmingham,AL,Southern Association of Colleges and Schools Commission on Colleges,2,46474.0,NaN,31650.0,31650.0,0.9848,0.1227,20000,8250,17500,18240,15750,17000,18240,18250,15500,17448,15563,15250,17500
44,102058,Selma,AL,NaN,2,15822.0,NaN,7410.0,7410.0,1.0000,0.9646,34300,9475,9500,PrivacySuppressed,PrivacySuppressed,9500,10775,PrivacySuppressed,PrivacySuppressed,9250,11000,9500,9500
45,102067,Tuscaloosa,AL,Southern Association of Colleges and Schools Commission on Colleges,1,12070.0,NaN,4467.0,8907.0,0.4429,0.4658,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed
46,102076,Boaz,AL,Southern Association of Colleges and Schools Commission on Colleges,1,11073.0,NaN,4800.0,8670.0,0.2657,0.4860,8000,5250,5903,5406,6000,5500,7017,5711,5500,6000,5500,5686,5500
47,102094,Mobile,AL,Southern Association of Colleges and Schools Commission on Colleges,1,19835.0,NaN,8396.0,16292.0,0.6146,0.3922,25000,9500,18000,17005,14750,15198,19382,19000,12500,17000,15000,17006,15000
48,102234,Mobile,AL,Southern Association of Colleges and Schools Commission on Colleges,2,51969.0,NaN,39464.0,39464.0,0.6667,0.3420,27000,14625,11750,18876,20000,18751,15750,16125,19500,19500,13000,14750,21425
49,102270,Tuscaloosa,AL,Southern Association of Colleges and Schools Commission on Colleges,2,21314.0,NaN,11092.0,11092.0,0.6949,0.8316,32500,9500,15000,15000,12500,15000,10250,15750,5500,22500,9500,15000,14000
50,102298,Talladega,AL,Southern Association of Colleges and Schools Commission on Colleges,2,22514.0,NaN,13571.0,13571.0,0.5789,0.8951,31990,9500,15125,21500,9500,16862,15000,18500,8235,16077,16487,16000,16000
51,102313,Montgomery,AL,Southern Association of Colleges and Schools Commission on Colleges,1,12383.0,NaN,4650.0,8520.0,0.4928,0.5122,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed
52,102368,Troy,AL,Southern Association of Colleges and Schools Commission on Colleges,1,19180.0,NaN,8908.0,16708.0,0.5330,0.4015,25030,11500,16086,14936,14250,13000,18750,17000,12000,16465,13053,15625,14250
53,102377,Tuskegee,AL,Southern Association of Colleges and Schools Commission on Colleges,2,39383.0,NaN,22170.0,22170.0,1.0000,0.5256,29090,10000,20000,19500,19500,19500,19750,21500,15000,20500,18675,19500,20000
54,102395,Daphne,AL,Southern Association of Colleges and Schools Commission on Colleges,2,NaN,NaN,NaN,NaN,0.2000,0.5340,24662,9307,15412,PrivacySuppressed,PrivacySuppressed,9153,15412,PrivacySuppressed,PrivacySuppressed,13973,11216,PrivacySuppressed,PrivacySuppressed
55,102429,Jasper,AL,Southern Association of Colleges and Schools Commission on Colleges,1,13681.0,NaN,5086.0,9214.0,0.3234,0.4372,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed
56,102553,Anchorage,AK,Northwest Commission on Colleges and Universities,1,19942.0,NaN,8580.0,24762.0,0.4840,0.2255,20500,9000,11908,12068,9167,8389,13703,13498,8750,11000,10500,11000,10500
57,102580,Palmer,AK,Association for Bibical Higher Educaiton,2,24759.0,NaN,9600.0,9600.0,NaN,0.6129,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed
58,102614,Fairbanks,AK,Northwest Commission on Colleges and Universities,1,18510.0,NaN,6657.0,20218.0,0.6066,0.2202,19500,9304,10873,11441,9500,9283,12500,12500,8405,10500,11000,10579,11000
59,102632,Juneau,AK,Northwest Commission on Colleges and Universities,1,16853.0,NaN,7092.0,19856.0,0.6092,0.1767,22438,8986,11157,10500,8974,7656,12500,12386,8450,10817,9500,11008,8139
60,102669,Anchorage,AK,Northwest Commission on Colleges and Universities,2,34990.0,NaN,20760.0,20760.0,0.5692,0.3492,21677,9500,14009,13000,16625,14000,15649,14250,14667,14363,14334,14250,14667
61,102711,Seward,AK,Council on Occupational Education,1,NaN,13924.0,NaN,NaN,NaN,0.0433,PrivacySuppressed,PrivacySuppressed,6467,PrivacySuppressed,PrivacySuppressed,5500,6992,5500,5500,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed
62,102845,Vancouver,WA,Accrediting Bureau of Health Education Schools,3,35613.0,NaN,22655.0,22655.0,0.3162,0.6195,14171,5904,12776,12783,10855,9500,13707,12783,10910,12783,11845,12731,12783
63,103501,Anchorage,AK,Accrediting Commission of Career Schools and Colleges,3,NaN,21369.0,NaN,NaN,0.2308,0.7406,9076,4750,8596,7199,6797,5965,9303,8435,6971,7478,9404,7540,9285
64,103741,Tucson,AZ,National Accrediting Commission of Career Arts and Sciences,3,NaN,19366.0,NaN,NaN,NaN,0.5730,12410,4750,8028,8028,8028,8028,9500,8028,8028,8028,9500,8028,8028
65,103893,Phoenix,AZ,Western Association of Schools and Colleges Accrediting Commission for Community and Junior Colleges,3,NaN,24471.0,NaN,NaN,0.6429,0.2056,9399,5500,9003,9360,9458,6212,9500,8999,9500,9093,9204,8964,9500
66,103909,Mesa,AZ,Western Association of Schools and Colleges Accrediting Commission for Community and Junior Colleges,3,NaN,25115.0,NaN,NaN,0.3250,0.2503,9399,5500,9003,9360,9458,6212,9500,8999,9500,9093,9204,8964,9500
67,103927,Tucson,AZ,Western Association of Schools and Colleges Accrediting Commission for Community and Junior Colleges,3,NaN,22025.0,NaN,NaN,0.5385,0.1891,9399,5500,9003,9360,9458,6212,9500,8999,9500,9093,9204,8964,9500
68,103945,Flagstaff,AZ,Accrediting Commission of Career Schools and Colleges,2,32164.0,NaN,16972.0,16972.0,NaN,0.8205,24625,7968,14966,19268,14771,15250,18161,16114,11557,18500,12850,15959,17664
69,103954,Tucson,AZ,National Accrediting Commission of Career Arts and Sciences,3,NaN,18306.0,NaN,NaN,NaN,0.7835,4733,3916,4062,PrivacySuppressed,PrivacySuppressed,5500,4225,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed
70,103963,Glendale,AZ,Accrediting Commission of Career Schools and Colleges,3,NaN,34346.0,NaN,NaN,NaN,0.6401,13000,6334,9500,9778,9166,9389,9500,9500,11285,9500,9500,9500,9500
71,104090,Phoenix,AZ,Accrediting Bureau of Health Education Schools,3,NaN,34841.0,NaN,NaN,0.3200,0.6924,9500,4750,9317,9500,14650,8927,9500,9308,17605,9425,9500,9403,9500
72,104151,Tempe,AZ,Higher Learning Commission,1,25621.0,NaN,10822.0,28336.0,0.7766,0.3026,20278,9148,13884,14375,13750,12750,16305,15000,12500,13750,14242,14000,14000
73,104160,Yuma,AZ,Higher Learning Commission,1,15407.0,NaN,2720.0,9710.0,0.3079,0.4516,5500,3500,4188,4528,2874,3250,6167,4500,3000,4000,3625,4000,3513
74,104179,Tucson,AZ,Higher Learning Commission,1,26712.0,NaN,12467.0,36366.0,0.7625,0.2896,20171,8250,13807,14340,14250,13820,16950,15000,12570,14000,14000,14000,14500
75,104188,Tucson,AZ,NaN,3,35552.0,NaN,23069.0,23069.0,1.0000,0.7295,43000,20000,38625,PrivacySuppressed,PrivacySuppressed,30750,37500,PrivacySuppressed,PrivacySuppressed,30750,30000,30750,30500
76,104346,Coolidge,AZ,Higher Learning Commission,1,10680.0,NaN,2580.0,11100.0,1.0000,0.4080,9169,6244,7540,6484,5500,5500,8891,7272,5500,7312,5500,6646,6470
77,104391,Lake Havasu City,AZ,National Accrediting Commission of Career Arts and Sciences,3,NaN,13737.0,NaN,NaN,NaN,0.5200,7389,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed
78,104425,Sierra Vista,AZ,Higher Learning Commission,1,11589.0,NaN,2040.0,6240.0,0.3355,0.3670,8239,5250,7000,5192,5500,4700,7357,6334,5250,6063,5500,6000,4688
79,104434,Flagstaff,AZ,National Accrediting Commission of Career Arts and Sciences,3,NaN,19017.0,NaN,NaN,NaN,0.5484,11746,4750,8028,8028,7805,7968,9500,8028,7978,8028,8028,8028,7983
80,104443,Chandler,AZ,National Accrediting Commission of Career Arts and Sciences,3,NaN,19232.0,NaN,NaN,NaN,0.6316,11746,4750,8028,8028,7805,7968,9500,8028,7978,8028,8028,8028,7983

In [98]:
inst_df1.to_csv('../data/reduced_inst_data.csv')